_STRINGS[1]	= "Error loading saved settings";
_STRINGS[2]	= "Please report this error at lotrointerface.com";
_STRINGS[3]	= "usage: /pets opens/closes the main window";
_STRINGS[4] = "Name";
_STRINGS[5] = "Family";
_STRINGS[6] = "Search";
_STRINGS[7] = "Rename";
_STRINGS[8] = "/cpet rename"; -- slash command used for renaming pets
_STRINGS[9] = "Show Quickslots Bar";
_STRINGS[10] = "Enter a new name for your current pet";
_STRINGS[11] = "When checked this pet will be added to the shortcut bar";
_STRINGS[12] = "Results:";
_STRINGS[13] = "Use command /pets to show or hide the main window";
_STRINGS[14] = "All";
_STRINGS[15] = "Update";
_STRINGS[16] = "Afficher uniquement les familiers connus";
_STRINGS[17] = "Tous disponibles";
_STRINGS[18] = "Familier par rangée";
_STRINGS[19] = "Droite > Bas";
_STRINGS[20] = "Gauche > Bas";
_STRINGS[21] = "Droite > Haut";
_STRINGS[22] = "Gauche > Haut";
_STRINGS[23] = "Haut > Gauche"
_STRINGS[24] = "Haut > Droite"
_STRINGS[25] = "Bas > Gauche"
_STRINGS[26] = "Bas > Droite"
_STRINGS[27] = "Orientation de la barre de raccourcis";