_STRINGS[1]	= "Error loading saved settings";
_STRINGS[2]	= "Please report this error at lotrointerface.com";
_STRINGS[3]	= "usage: /pets opens/closes the main window";
_STRINGS[4] = "Name";
_STRINGS[5] = "Family";
_STRINGS[6] = "Search";
_STRINGS[7] = "Rename";
_STRINGS[8] = "/cpet rename"; -- slash command used for renaming pets
_STRINGS[9] = "Show Quickslots Bar";
_STRINGS[10] = "Enter a new name for your current pet";
_STRINGS[11] = "When checked this pet will be added to the shortcut bar";
_STRINGS[12] = "Results:";
_STRINGS[13] = "Use command /pets to show or hide the main window";
_STRINGS[14] = "All";
_STRINGS[15] = "Update";
_STRINGS[16] = "Show only known pets";
_STRINGS[17] = "All available";
_STRINGS[18] = "Pets per row";
_STRINGS[19] = "Right > Down";
_STRINGS[20] = "Left > Down";
_STRINGS[21] = "Right > Up";
_STRINGS[22] = "Left > Up";
_STRINGS[23] = "Up > Left"
_STRINGS[24] = "Up > Right"
_STRINGS[25] = "Down > Left"
_STRINGS[26] = "Down > Right"
_STRINGS[27] = "Quickslot bar orientation";
