_STRINGS[1]	= "Fehler beim Laden der Einstellungen!";
_STRINGS[2]	= "Bitte melde diesen Fehler auf lotrointerface.com";
_STRINGS[3]	= "Nutzung: /pets \195\182ffnet/schlie\195\159t das Hauptfenster";
_STRINGS[4] = "Name";
_STRINGS[5] = "Familie";
_STRINGS[6] = "Suche";
_STRINGS[7] = "Umbenennen";
_STRINGS[8] = "/zwb umbenennen"; -- slash command used for renaming pets
_STRINGS[9] = "Quickslots Bar anzeigen";
_STRINGS[10] = "Gib einen neuen Namen f\195\188r dein aktuelles Tier ein";
_STRINGS[11] = "Tier erscheint in der Quickslots Bar wenn angehakt";
_STRINGS[12] = "Ergebnisse:";
_STRINGS[13] = "Nutze den Befehl /pets um das Hauptfenster anzuzeigen / zu verbergen";
_STRINGS[14] = "Alle";
_STRINGS[15] = "Update";
_STRINGS[16] = "Nur bekannte Begleiter anzeigen";
_STRINGS[17] = "Alle verfügbaren";
_STRINGS[18] = "Begleiter pro Reihe";
_STRINGS[19] = "Rechts > Unten";
_STRINGS[20] = "Links > Unten";
_STRINGS[21] = "Rechts > Oben";
_STRINGS[22] = "Links > Oben";
_STRINGS[23] = "Oben > Links"
_STRINGS[24] = "Oben > Rechts"
_STRINGS[25] = "Unten > Links"
_STRINGS[26] = "Unten > Rechts"
_STRINGS[27] = "Ausrichtung der Quickslots";
