name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Update'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'Pets_${{ github.event.inputs.tag }}.zip'
        exclusions: '*.git* *.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'Pets_${{ github.event.inputs.tag }}.zip'
        commit: master
        bodyFile: Release.md
        tag: ${{ github.event.inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
